version: '3.5'
services:
  pg_quarkus_benchmark:
    image: myself/quarkus-benchmark-pg
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
